# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170131_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgainsation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
