# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20170131_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgainsationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Orgainsation',
            new_name='Organisation',
        ),
        migrations.AddField(
            model_name='orgainsationaddress',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Organisation'),
        ),
    ]
