# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20170131_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgainsationAddress',
            new_name='OrganisationAddress',
        ),
    ]
