# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170131_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contacts.Organisation'),
        ),
    ]
