# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170131_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
