# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20170131_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='first_line',
        ),
    ]
